version: '3.2'

services:

  # -------------------------------------------------------------
  # 
  # -------------------------------------------------------------
  nginx:
    image: nginx:alpine
    ports:
      - "9080:80"
    volumes:
      - ./conf.d:/etc/nginx/conf.d:ro

