language: java

dist: trusty

jdk:
  - openjdk8

before_script:
 - "echo $JAVA_OPTS"
 - "export JAVA_OPTS=-Xmx2048m"
 - "echo $JAVA_OPTS"
 - "ulimit -a"
 - "ulimit -u 2048"
 - "ulimit -a"
 - "umask 022"
 - "mkdir inputs"

sudo: false

# Use Docker for multi-component testing
services:
  - docker

# Run a Redis instance to test against
#before_install:
#- docker pull redis
#- docker run -d -p 127.0.0.1:6379:6379 redis
#- docker pull ukwa/tinycdxserver
#- docker ps -a
