name: crawler-integration-tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup the UID env var
        run: echo "CRAWL_UID=$(id -u)" >> $GITHUB_ENV
      - name: Check the Docker Compose config
        run: docker-compose config
      - name: Build the containers
        run: docker-compose build
      - name: Set up output folders so that permissions are correct
        run: |
            mkdir -p target/testing/heritrix/output
            mkdir -p target/testing/heritrix/scratch
            mkdir -p target/testing/heritrix/state
            mkdir -p target/testing/heritrix/wren
      - name: Spin up the crawler
        run: docker-compose up -d heritrix
      - name: Show what is running
        run: docker ps
      - name: Run integration tests
        run: docker-compose run robot
      - name: Show what Heritrix logged, even if the tests failed
        if: ${{ always() }}
        run: docker-compose logs heritrix
      # Make integration test results available, even if the tests failed
      - uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: robot-ci-results
          path: integration-test/results/
          if-no-files-found: error
