name: crawler-integration-tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Report which UID is in use (must match the UID env var)
        run: id
      - name: Setup the UID env var
        run: echo "CRAWL_UID=$(id -u)" >> $GITHUB_ENV
      - name: Check the UID
        run: echo $CRAWL_UID
      - name: Check the Docker Compose config
        run: docker-compose config
      - name: Build the containers
        run: docker-compose build
      - name: Set up output folders
        run: |
            mkdir -p target/testing
            chmod -R a+rwx target
            ls -l
      - run: chmod -R a+rwx .
      - run: ls -l
      - name: Spin up the crawler
        run: docker-compose up -d heritrix
      - name: Show what is running
        run: docker ps
      - run: docker-compose exec heritrix ls -l
      - run: docker-compose exec heritrix ls -l /
      - run: docker-compose exec heritrix ls -l /heritrix
      - run: docker-compose exec heritrix ls -l /heritrix/output
      - name: Run integration tests
        run: docker-compose run robot
      - name: Show what Heritrix logged, even if the tests failed
        if: ${{ always() }}
        run: docker-compose logs heritrix
      # Make integration test results available, even if the tests failed
      - uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: robot-ci-results
          path: integration-test/results/
          if-no-files-found: error
