name: docker-compose-actions-workflow
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    # Set up a UID variable as the Docker Compose setup uses that when running:
    env:
      UID: 0
    steps:
      - uses: actions/checkout@v2
      - name: Build the containers
        run: docker-compose build
      - name: Spin up the crawler
        run: docker-compose up -d heritrix
      - name: Show what is running
        run: docker ps
      - name: Run integration tests
        run: docker-compose run robot
