name: publish-docker-image
on:
  push:
    tags:
      - 'v*'
  workflow_run:
    workflows: ["crawler-integration-tests"]
    branches: [master]
    types: 
      - completed
jobs:
  push_to_registries:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ukwa/heritrix    
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Log in to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
